// flow-typed signature: 75507d8807c4c995fd54650d8776fb0b
// flow-typed version: <<STUB>>/@novnc/novnc_v^1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@novnc/novnc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@novnc/novnc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@novnc/novnc/core/base64' {
  declare module.exports: any;
}

declare module '@novnc/novnc/core/des' {
  declare module.exports: any;
}

declare module '@novnc/novnc/core/display' {
  declare module.exports: any;
}

declare module '@novnc/novnc/core/encodings' {
  declare module.exports: any;
}

declare module '@novnc/novnc/core/inflator' {
  declare module.exports: any;
}

declare module '@novnc/novnc/core/input/domkeytable' {
  declare module.exports: any;
}

declare module '@novnc/novnc/core/input/fixedkeys' {
  declare module.exports: any;
}

declare module '@novnc/novnc/core/input/keyboard' {
  declare module.exports: any;
}

declare module '@novnc/novnc/core/input/keysym' {
  declare module.exports: any;
}

declare module '@novnc/novnc/core/input/keysymdef' {
  declare module.exports: any;
}

declare module '@novnc/novnc/core/input/mouse' {
  declare module.exports: any;
}

declare module '@novnc/novnc/core/input/util' {
  declare module.exports: any;
}

declare module '@novnc/novnc/core/input/vkeys' {
  declare module.exports: any;
}

declare module '@novnc/novnc/core/input/xtscancodes' {
  declare module.exports: any;
}

declare module '@novnc/novnc/core/rfb' {
  declare module.exports: any;
}

declare module '@novnc/novnc/core/util/browser' {
  declare module.exports: any;
}

declare module '@novnc/novnc/core/util/events' {
  declare module.exports: any;
}

declare module '@novnc/novnc/core/util/eventtarget' {
  declare module.exports: any;
}

declare module '@novnc/novnc/core/util/logging' {
  declare module.exports: any;
}

declare module '@novnc/novnc/core/util/polyfill' {
  declare module.exports: any;
}

declare module '@novnc/novnc/core/util/strings' {
  declare module.exports: any;
}

declare module '@novnc/novnc/core/websock' {
  declare module.exports: any;
}

declare module '@novnc/novnc/vendor/pako/lib/utils/common' {
  declare module.exports: any;
}

declare module '@novnc/novnc/vendor/pako/lib/zlib/adler32' {
  declare module.exports: any;
}

declare module '@novnc/novnc/vendor/pako/lib/zlib/constants' {
  declare module.exports: any;
}

declare module '@novnc/novnc/vendor/pako/lib/zlib/crc32' {
  declare module.exports: any;
}

declare module '@novnc/novnc/vendor/pako/lib/zlib/deflate' {
  declare module.exports: any;
}

declare module '@novnc/novnc/vendor/pako/lib/zlib/gzheader' {
  declare module.exports: any;
}

declare module '@novnc/novnc/vendor/pako/lib/zlib/inffast' {
  declare module.exports: any;
}

declare module '@novnc/novnc/vendor/pako/lib/zlib/inflate' {
  declare module.exports: any;
}

declare module '@novnc/novnc/vendor/pako/lib/zlib/inftrees' {
  declare module.exports: any;
}

declare module '@novnc/novnc/vendor/pako/lib/zlib/messages' {
  declare module.exports: any;
}

declare module '@novnc/novnc/vendor/pako/lib/zlib/trees' {
  declare module.exports: any;
}

declare module '@novnc/novnc/vendor/pako/lib/zlib/zstream' {
  declare module.exports: any;
}

// Filename aliases
declare module '@novnc/novnc/core/base64.js' {
  declare module.exports: $Exports<'@novnc/novnc/core/base64'>;
}
declare module '@novnc/novnc/core/des.js' {
  declare module.exports: $Exports<'@novnc/novnc/core/des'>;
}
declare module '@novnc/novnc/core/display.js' {
  declare module.exports: $Exports<'@novnc/novnc/core/display'>;
}
declare module '@novnc/novnc/core/encodings.js' {
  declare module.exports: $Exports<'@novnc/novnc/core/encodings'>;
}
declare module '@novnc/novnc/core/inflator.js' {
  declare module.exports: $Exports<'@novnc/novnc/core/inflator'>;
}
declare module '@novnc/novnc/core/input/domkeytable.js' {
  declare module.exports: $Exports<'@novnc/novnc/core/input/domkeytable'>;
}
declare module '@novnc/novnc/core/input/fixedkeys.js' {
  declare module.exports: $Exports<'@novnc/novnc/core/input/fixedkeys'>;
}
declare module '@novnc/novnc/core/input/keyboard.js' {
  declare module.exports: $Exports<'@novnc/novnc/core/input/keyboard'>;
}
declare module '@novnc/novnc/core/input/keysym.js' {
  declare module.exports: $Exports<'@novnc/novnc/core/input/keysym'>;
}
declare module '@novnc/novnc/core/input/keysymdef.js' {
  declare module.exports: $Exports<'@novnc/novnc/core/input/keysymdef'>;
}
declare module '@novnc/novnc/core/input/mouse.js' {
  declare module.exports: $Exports<'@novnc/novnc/core/input/mouse'>;
}
declare module '@novnc/novnc/core/input/util.js' {
  declare module.exports: $Exports<'@novnc/novnc/core/input/util'>;
}
declare module '@novnc/novnc/core/input/vkeys.js' {
  declare module.exports: $Exports<'@novnc/novnc/core/input/vkeys'>;
}
declare module '@novnc/novnc/core/input/xtscancodes.js' {
  declare module.exports: $Exports<'@novnc/novnc/core/input/xtscancodes'>;
}
declare module '@novnc/novnc/core/rfb.js' {
  declare module.exports: $Exports<'@novnc/novnc/core/rfb'>;
}
declare module '@novnc/novnc/core/util/browser.js' {
  declare module.exports: $Exports<'@novnc/novnc/core/util/browser'>;
}
declare module '@novnc/novnc/core/util/events.js' {
  declare module.exports: $Exports<'@novnc/novnc/core/util/events'>;
}
declare module '@novnc/novnc/core/util/eventtarget.js' {
  declare module.exports: $Exports<'@novnc/novnc/core/util/eventtarget'>;
}
declare module '@novnc/novnc/core/util/logging.js' {
  declare module.exports: $Exports<'@novnc/novnc/core/util/logging'>;
}
declare module '@novnc/novnc/core/util/polyfill.js' {
  declare module.exports: $Exports<'@novnc/novnc/core/util/polyfill'>;
}
declare module '@novnc/novnc/core/util/strings.js' {
  declare module.exports: $Exports<'@novnc/novnc/core/util/strings'>;
}
declare module '@novnc/novnc/core/websock.js' {
  declare module.exports: $Exports<'@novnc/novnc/core/websock'>;
}
declare module '@novnc/novnc/vendor/pako/lib/utils/common.js' {
  declare module.exports: $Exports<'@novnc/novnc/vendor/pako/lib/utils/common'>;
}
declare module '@novnc/novnc/vendor/pako/lib/zlib/adler32.js' {
  declare module.exports: $Exports<'@novnc/novnc/vendor/pako/lib/zlib/adler32'>;
}
declare module '@novnc/novnc/vendor/pako/lib/zlib/constants.js' {
  declare module.exports: $Exports<'@novnc/novnc/vendor/pako/lib/zlib/constants'>;
}
declare module '@novnc/novnc/vendor/pako/lib/zlib/crc32.js' {
  declare module.exports: $Exports<'@novnc/novnc/vendor/pako/lib/zlib/crc32'>;
}
declare module '@novnc/novnc/vendor/pako/lib/zlib/deflate.js' {
  declare module.exports: $Exports<'@novnc/novnc/vendor/pako/lib/zlib/deflate'>;
}
declare module '@novnc/novnc/vendor/pako/lib/zlib/gzheader.js' {
  declare module.exports: $Exports<'@novnc/novnc/vendor/pako/lib/zlib/gzheader'>;
}
declare module '@novnc/novnc/vendor/pako/lib/zlib/inffast.js' {
  declare module.exports: $Exports<'@novnc/novnc/vendor/pako/lib/zlib/inffast'>;
}
declare module '@novnc/novnc/vendor/pako/lib/zlib/inflate.js' {
  declare module.exports: $Exports<'@novnc/novnc/vendor/pako/lib/zlib/inflate'>;
}
declare module '@novnc/novnc/vendor/pako/lib/zlib/inftrees.js' {
  declare module.exports: $Exports<'@novnc/novnc/vendor/pako/lib/zlib/inftrees'>;
}
declare module '@novnc/novnc/vendor/pako/lib/zlib/messages.js' {
  declare module.exports: $Exports<'@novnc/novnc/vendor/pako/lib/zlib/messages'>;
}
declare module '@novnc/novnc/vendor/pako/lib/zlib/trees.js' {
  declare module.exports: $Exports<'@novnc/novnc/vendor/pako/lib/zlib/trees'>;
}
declare module '@novnc/novnc/vendor/pako/lib/zlib/zstream.js' {
  declare module.exports: $Exports<'@novnc/novnc/vendor/pako/lib/zlib/zstream'>;
}
