// flow-typed signature: 26c2d35751a8fd89865b7d3a539ca886
// flow-typed version: <<STUB>>/blob-polyfill_v^2.0.20171115/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'blob-polyfill'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'blob-polyfill' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'blob-polyfill/Blob' {
  declare module.exports: any;
}

// Filename aliases
declare module 'blob-polyfill/Blob.js' {
  declare module.exports: $Exports<'blob-polyfill/Blob'>;
}
