// flow-typed signature: 25bbf898d3947c48a884294a8bd99712
// flow-typed version: <<STUB>>/des-vnc_v1.0.0/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'des-vnc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'des-vnc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'des-vnc/des' {
  declare module.exports: any;
}

declare module 'des-vnc/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'des-vnc/des.js' {
  declare module.exports: $Exports<'des-vnc/des'>;
}
declare module 'des-vnc/test/index.js' {
  declare module.exports: $Exports<'des-vnc/test/index'>;
}
