// flow-typed signature: 237c0b7dea8cc38cfcb3dad1ba8fd4cb
// flow-typed version: <<STUB>>/react-360-web_v^1.0.1/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-360-web'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-360-web' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-360-web/js/Audio/AudioTypes' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Audio/getSupportedFormats' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Audio/MediaError' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Audio/OVRAudio' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Audio/VRAudioBufferManager' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Audio/VRAudioBufferSource' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Audio/VRAudioComponent' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Audio/VRAudioContext' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Bridge/Bridge' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Bridge/WebWorkerBridge' {
  declare module.exports: any;
}

declare module 'react-360-web/js/bundleFromLocation' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Compositor/Audio/AudioInstance' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Compositor/Audio/AudioNode' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Compositor/Audio/Types' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Compositor/Compositor' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Compositor/Cursor' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Compositor/Environment/Environment' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Compositor/Environment/StereoBasicTextureMaterial' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Compositor/Environment/StereoShaderLib' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Compositor/Environment/StereoTextureUniforms' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Compositor/Environment/Types' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Compositor/Glyphs' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Compositor/Location' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Compositor/Overlay' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Compositor/Surface' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Compositor/Video/BrowserVideoPlayer' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Compositor/Video/Types' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Compositor/Video/VideoPlayerManager' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Compositor/VRState' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Controls/__tests__/InputChannels-test' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Controls/CameraControllers/DeviceOrientationCameraController' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Controls/CameraControllers/MousePanCameraController' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Controls/CameraControllers/ScrollPanCameraController' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Controls/CameraControllers/Types' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Controls/Controls' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Controls/InputChannels/GamepadInputChannel' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Controls/InputChannels/KeyboardInputChannel' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Controls/InputChannels/MouseInputChannel' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Controls/InputChannels/TouchInputChannel' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Controls/InputChannels/Types' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Controls/Raycasters/ControllerRaycaster' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Controls/Raycasters/MouseRaycaster' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Controls/Raycasters/TouchRaycaster' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Controls/Raycasters/Types' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Controls/Types' {
  declare module.exports: any;
}

declare module 'react-360-web/js/createRootView' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Events/MediaEvent' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Executor/ReactExecutor' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Executor/ReactExecutorIframe' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Executor/ReactExecutorWebWorker' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Loaders/GLTF2ModelLoader' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Loaders/ModelLoaderRegistry' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Loaders/ObjModelLoader' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Loaders/WavefrontOBJ/__tests__/MTLParser-test' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Loaders/WavefrontOBJ/__tests__/OBJGroup-test' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Loaders/WavefrontOBJ/__tests__/OBJLoader-test' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Loaders/WavefrontOBJ/__tests__/OBJParser-test' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Loaders/WavefrontOBJ/MTLLoader' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Loaders/WavefrontOBJ/MTLParser' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Loaders/WavefrontOBJ/OBJGroup' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Loaders/WavefrontOBJ/OBJLoader' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Loaders/WavefrontOBJ/OBJParser' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Loaders/WavefrontOBJ/OBJTypes' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/__tests__/Module-test' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/AndroidConstants' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/AsyncLocalStorage' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/AudioModule' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/ControllerInfo' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/DeviceInfo' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/EnvironmentModule' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/ExternalAssets' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/GlyphTextures' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/History' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/LinkingManager' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/Location' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/LocationObserver' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/Module' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/Networking' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/PlatformConstants' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/RCTAudioModule' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/RCTExceptionsManager' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/RCTSourceCode' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/RCTVideoModule' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/ReactVRConstants' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/Timing' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/UIManager' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/VideoModule' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Modules/WebSocketModule' {
  declare module.exports: any;
}

declare module 'react-360-web/js/OVRUI/FourByFourRect/VectorGeometry' {
  declare module.exports: any;
}

declare module 'react-360-web/js/OVRUI/SDFFont/DefaultFont' {
  declare module.exports: any;
}

declare module 'react-360-web/js/OVRUI/SDFFont/SDFFont' {
  declare module.exports: any;
}

declare module 'react-360-web/js/OVRUI/UIView/GuiSys' {
  declare module.exports: any;
}

declare module 'react-360-web/js/OVRUI/UIView/GuiSysEvent' {
  declare module.exports: any;
}

declare module 'react-360-web/js/OVRUI/UIView/UIView' {
  declare module.exports: any;
}

declare module 'react-360-web/js/OVRUI/UIView/UIViewUtil' {
  declare module.exports: any;
}

declare module 'react-360-web/js/ReactInstance' {
  declare module.exports: any;
}

declare module 'react-360-web/js/ReactNativeContext' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Runtime/Runtime' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/__tests__/merge-test' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/__tests__/RCTVideoPlayer-test' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/__tests__/RefCountCache-test' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/__tests__/TextureManager-test' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/createRemoteImageManager' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/CubePano' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/extractURL' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/fetchResource' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/FlexboxImplementation' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/HPano' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/isPositive' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/Math' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/merge' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/RCTBindedResource' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/RCTHeadModel' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/RCTInputControls' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/RCTResourceManager' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/RCTVideoPlayer' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/RefCountCache' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/ResourceManager' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/StereoOffsetRepeats' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/TextureManager' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Utils/Yoga.bundle' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Video/BasicVideoPlayer' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Video/getSupportedFormats' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Video/OVRVideo' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Video/VRVideoComponent' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Video/VRVideoPlayer' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/__tests__/BaseMesh-test' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/__tests__/BaseView-test' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/__tests__/Image-test' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/__tests__/Model-test' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/__tests__/Text-test' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/__tests__/View-test' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/AmbientLight' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/BaseMesh' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/BaseView' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/Box' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/Cylinder' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/CylindricalPanel' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/DirectionalLight' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/Image' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/LiveEnvCamera' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/Model' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/Pano' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/Plane' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/PointLight' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/Prefetch' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/QuadPanel' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/RawText' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/Scene' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/Sound' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/Sphere' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/SpotLight' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/Text' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/Video' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/VideoPano' {
  declare module.exports: any;
}

declare module 'react-360-web/js/Views/View' {
  declare module.exports: any;
}

declare module 'react-360-web/React360' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-360-web/js/Audio/AudioTypes.js' {
  declare module.exports: $Exports<'react-360-web/js/Audio/AudioTypes'>;
}
declare module 'react-360-web/js/Audio/getSupportedFormats.js' {
  declare module.exports: $Exports<'react-360-web/js/Audio/getSupportedFormats'>;
}
declare module 'react-360-web/js/Audio/MediaError.js' {
  declare module.exports: $Exports<'react-360-web/js/Audio/MediaError'>;
}
declare module 'react-360-web/js/Audio/OVRAudio.js' {
  declare module.exports: $Exports<'react-360-web/js/Audio/OVRAudio'>;
}
declare module 'react-360-web/js/Audio/VRAudioBufferManager.js' {
  declare module.exports: $Exports<'react-360-web/js/Audio/VRAudioBufferManager'>;
}
declare module 'react-360-web/js/Audio/VRAudioBufferSource.js' {
  declare module.exports: $Exports<'react-360-web/js/Audio/VRAudioBufferSource'>;
}
declare module 'react-360-web/js/Audio/VRAudioComponent.js' {
  declare module.exports: $Exports<'react-360-web/js/Audio/VRAudioComponent'>;
}
declare module 'react-360-web/js/Audio/VRAudioContext.js' {
  declare module.exports: $Exports<'react-360-web/js/Audio/VRAudioContext'>;
}
declare module 'react-360-web/js/Bridge/Bridge.js' {
  declare module.exports: $Exports<'react-360-web/js/Bridge/Bridge'>;
}
declare module 'react-360-web/js/Bridge/WebWorkerBridge.js' {
  declare module.exports: $Exports<'react-360-web/js/Bridge/WebWorkerBridge'>;
}
declare module 'react-360-web/js/bundleFromLocation.js' {
  declare module.exports: $Exports<'react-360-web/js/bundleFromLocation'>;
}
declare module 'react-360-web/js/Compositor/Audio/AudioInstance.js' {
  declare module.exports: $Exports<'react-360-web/js/Compositor/Audio/AudioInstance'>;
}
declare module 'react-360-web/js/Compositor/Audio/AudioNode.js' {
  declare module.exports: $Exports<'react-360-web/js/Compositor/Audio/AudioNode'>;
}
declare module 'react-360-web/js/Compositor/Audio/Types.js' {
  declare module.exports: $Exports<'react-360-web/js/Compositor/Audio/Types'>;
}
declare module 'react-360-web/js/Compositor/Compositor.js' {
  declare module.exports: $Exports<'react-360-web/js/Compositor/Compositor'>;
}
declare module 'react-360-web/js/Compositor/Cursor.js' {
  declare module.exports: $Exports<'react-360-web/js/Compositor/Cursor'>;
}
declare module 'react-360-web/js/Compositor/Environment/Environment.js' {
  declare module.exports: $Exports<'react-360-web/js/Compositor/Environment/Environment'>;
}
declare module 'react-360-web/js/Compositor/Environment/StereoBasicTextureMaterial.js' {
  declare module.exports: $Exports<'react-360-web/js/Compositor/Environment/StereoBasicTextureMaterial'>;
}
declare module 'react-360-web/js/Compositor/Environment/StereoShaderLib.js' {
  declare module.exports: $Exports<'react-360-web/js/Compositor/Environment/StereoShaderLib'>;
}
declare module 'react-360-web/js/Compositor/Environment/StereoTextureUniforms.js' {
  declare module.exports: $Exports<'react-360-web/js/Compositor/Environment/StereoTextureUniforms'>;
}
declare module 'react-360-web/js/Compositor/Environment/Types.js' {
  declare module.exports: $Exports<'react-360-web/js/Compositor/Environment/Types'>;
}
declare module 'react-360-web/js/Compositor/Glyphs.js' {
  declare module.exports: $Exports<'react-360-web/js/Compositor/Glyphs'>;
}
declare module 'react-360-web/js/Compositor/Location.js' {
  declare module.exports: $Exports<'react-360-web/js/Compositor/Location'>;
}
declare module 'react-360-web/js/Compositor/Overlay.js' {
  declare module.exports: $Exports<'react-360-web/js/Compositor/Overlay'>;
}
declare module 'react-360-web/js/Compositor/Surface.js' {
  declare module.exports: $Exports<'react-360-web/js/Compositor/Surface'>;
}
declare module 'react-360-web/js/Compositor/Video/BrowserVideoPlayer.js' {
  declare module.exports: $Exports<'react-360-web/js/Compositor/Video/BrowserVideoPlayer'>;
}
declare module 'react-360-web/js/Compositor/Video/Types.js' {
  declare module.exports: $Exports<'react-360-web/js/Compositor/Video/Types'>;
}
declare module 'react-360-web/js/Compositor/Video/VideoPlayerManager.js' {
  declare module.exports: $Exports<'react-360-web/js/Compositor/Video/VideoPlayerManager'>;
}
declare module 'react-360-web/js/Compositor/VRState.js' {
  declare module.exports: $Exports<'react-360-web/js/Compositor/VRState'>;
}
declare module 'react-360-web/js/Controls/__tests__/InputChannels-test.js' {
  declare module.exports: $Exports<'react-360-web/js/Controls/__tests__/InputChannels-test'>;
}
declare module 'react-360-web/js/Controls/CameraControllers/DeviceOrientationCameraController.js' {
  declare module.exports: $Exports<'react-360-web/js/Controls/CameraControllers/DeviceOrientationCameraController'>;
}
declare module 'react-360-web/js/Controls/CameraControllers/MousePanCameraController.js' {
  declare module.exports: $Exports<'react-360-web/js/Controls/CameraControllers/MousePanCameraController'>;
}
declare module 'react-360-web/js/Controls/CameraControllers/ScrollPanCameraController.js' {
  declare module.exports: $Exports<'react-360-web/js/Controls/CameraControllers/ScrollPanCameraController'>;
}
declare module 'react-360-web/js/Controls/CameraControllers/Types.js' {
  declare module.exports: $Exports<'react-360-web/js/Controls/CameraControllers/Types'>;
}
declare module 'react-360-web/js/Controls/Controls.js' {
  declare module.exports: $Exports<'react-360-web/js/Controls/Controls'>;
}
declare module 'react-360-web/js/Controls/InputChannels/GamepadInputChannel.js' {
  declare module.exports: $Exports<'react-360-web/js/Controls/InputChannels/GamepadInputChannel'>;
}
declare module 'react-360-web/js/Controls/InputChannels/KeyboardInputChannel.js' {
  declare module.exports: $Exports<'react-360-web/js/Controls/InputChannels/KeyboardInputChannel'>;
}
declare module 'react-360-web/js/Controls/InputChannels/MouseInputChannel.js' {
  declare module.exports: $Exports<'react-360-web/js/Controls/InputChannels/MouseInputChannel'>;
}
declare module 'react-360-web/js/Controls/InputChannels/TouchInputChannel.js' {
  declare module.exports: $Exports<'react-360-web/js/Controls/InputChannels/TouchInputChannel'>;
}
declare module 'react-360-web/js/Controls/InputChannels/Types.js' {
  declare module.exports: $Exports<'react-360-web/js/Controls/InputChannels/Types'>;
}
declare module 'react-360-web/js/Controls/Raycasters/ControllerRaycaster.js' {
  declare module.exports: $Exports<'react-360-web/js/Controls/Raycasters/ControllerRaycaster'>;
}
declare module 'react-360-web/js/Controls/Raycasters/MouseRaycaster.js' {
  declare module.exports: $Exports<'react-360-web/js/Controls/Raycasters/MouseRaycaster'>;
}
declare module 'react-360-web/js/Controls/Raycasters/TouchRaycaster.js' {
  declare module.exports: $Exports<'react-360-web/js/Controls/Raycasters/TouchRaycaster'>;
}
declare module 'react-360-web/js/Controls/Raycasters/Types.js' {
  declare module.exports: $Exports<'react-360-web/js/Controls/Raycasters/Types'>;
}
declare module 'react-360-web/js/Controls/Types.js' {
  declare module.exports: $Exports<'react-360-web/js/Controls/Types'>;
}
declare module 'react-360-web/js/createRootView.js' {
  declare module.exports: $Exports<'react-360-web/js/createRootView'>;
}
declare module 'react-360-web/js/Events/MediaEvent.js' {
  declare module.exports: $Exports<'react-360-web/js/Events/MediaEvent'>;
}
declare module 'react-360-web/js/Executor/ReactExecutor.js' {
  declare module.exports: $Exports<'react-360-web/js/Executor/ReactExecutor'>;
}
declare module 'react-360-web/js/Executor/ReactExecutorIframe.js' {
  declare module.exports: $Exports<'react-360-web/js/Executor/ReactExecutorIframe'>;
}
declare module 'react-360-web/js/Executor/ReactExecutorWebWorker.js' {
  declare module.exports: $Exports<'react-360-web/js/Executor/ReactExecutorWebWorker'>;
}
declare module 'react-360-web/js/Loaders/GLTF2ModelLoader.js' {
  declare module.exports: $Exports<'react-360-web/js/Loaders/GLTF2ModelLoader'>;
}
declare module 'react-360-web/js/Loaders/ModelLoaderRegistry.js' {
  declare module.exports: $Exports<'react-360-web/js/Loaders/ModelLoaderRegistry'>;
}
declare module 'react-360-web/js/Loaders/ObjModelLoader.js' {
  declare module.exports: $Exports<'react-360-web/js/Loaders/ObjModelLoader'>;
}
declare module 'react-360-web/js/Loaders/WavefrontOBJ/__tests__/MTLParser-test.js' {
  declare module.exports: $Exports<'react-360-web/js/Loaders/WavefrontOBJ/__tests__/MTLParser-test'>;
}
declare module 'react-360-web/js/Loaders/WavefrontOBJ/__tests__/OBJGroup-test.js' {
  declare module.exports: $Exports<'react-360-web/js/Loaders/WavefrontOBJ/__tests__/OBJGroup-test'>;
}
declare module 'react-360-web/js/Loaders/WavefrontOBJ/__tests__/OBJLoader-test.js' {
  declare module.exports: $Exports<'react-360-web/js/Loaders/WavefrontOBJ/__tests__/OBJLoader-test'>;
}
declare module 'react-360-web/js/Loaders/WavefrontOBJ/__tests__/OBJParser-test.js' {
  declare module.exports: $Exports<'react-360-web/js/Loaders/WavefrontOBJ/__tests__/OBJParser-test'>;
}
declare module 'react-360-web/js/Loaders/WavefrontOBJ/MTLLoader.js' {
  declare module.exports: $Exports<'react-360-web/js/Loaders/WavefrontOBJ/MTLLoader'>;
}
declare module 'react-360-web/js/Loaders/WavefrontOBJ/MTLParser.js' {
  declare module.exports: $Exports<'react-360-web/js/Loaders/WavefrontOBJ/MTLParser'>;
}
declare module 'react-360-web/js/Loaders/WavefrontOBJ/OBJGroup.js' {
  declare module.exports: $Exports<'react-360-web/js/Loaders/WavefrontOBJ/OBJGroup'>;
}
declare module 'react-360-web/js/Loaders/WavefrontOBJ/OBJLoader.js' {
  declare module.exports: $Exports<'react-360-web/js/Loaders/WavefrontOBJ/OBJLoader'>;
}
declare module 'react-360-web/js/Loaders/WavefrontOBJ/OBJParser.js' {
  declare module.exports: $Exports<'react-360-web/js/Loaders/WavefrontOBJ/OBJParser'>;
}
declare module 'react-360-web/js/Loaders/WavefrontOBJ/OBJTypes.js' {
  declare module.exports: $Exports<'react-360-web/js/Loaders/WavefrontOBJ/OBJTypes'>;
}
declare module 'react-360-web/js/Modules/__tests__/Module-test.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/__tests__/Module-test'>;
}
declare module 'react-360-web/js/Modules/AndroidConstants.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/AndroidConstants'>;
}
declare module 'react-360-web/js/Modules/AsyncLocalStorage.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/AsyncLocalStorage'>;
}
declare module 'react-360-web/js/Modules/AudioModule.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/AudioModule'>;
}
declare module 'react-360-web/js/Modules/ControllerInfo.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/ControllerInfo'>;
}
declare module 'react-360-web/js/Modules/DeviceInfo.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/DeviceInfo'>;
}
declare module 'react-360-web/js/Modules/EnvironmentModule.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/EnvironmentModule'>;
}
declare module 'react-360-web/js/Modules/ExternalAssets.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/ExternalAssets'>;
}
declare module 'react-360-web/js/Modules/GlyphTextures.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/GlyphTextures'>;
}
declare module 'react-360-web/js/Modules/History.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/History'>;
}
declare module 'react-360-web/js/Modules/LinkingManager.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/LinkingManager'>;
}
declare module 'react-360-web/js/Modules/Location.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/Location'>;
}
declare module 'react-360-web/js/Modules/LocationObserver.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/LocationObserver'>;
}
declare module 'react-360-web/js/Modules/Module.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/Module'>;
}
declare module 'react-360-web/js/Modules/Networking.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/Networking'>;
}
declare module 'react-360-web/js/Modules/PlatformConstants.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/PlatformConstants'>;
}
declare module 'react-360-web/js/Modules/RCTAudioModule.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/RCTAudioModule'>;
}
declare module 'react-360-web/js/Modules/RCTExceptionsManager.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/RCTExceptionsManager'>;
}
declare module 'react-360-web/js/Modules/RCTSourceCode.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/RCTSourceCode'>;
}
declare module 'react-360-web/js/Modules/RCTVideoModule.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/RCTVideoModule'>;
}
declare module 'react-360-web/js/Modules/ReactVRConstants.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/ReactVRConstants'>;
}
declare module 'react-360-web/js/Modules/Timing.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/Timing'>;
}
declare module 'react-360-web/js/Modules/UIManager.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/UIManager'>;
}
declare module 'react-360-web/js/Modules/VideoModule.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/VideoModule'>;
}
declare module 'react-360-web/js/Modules/WebSocketModule.js' {
  declare module.exports: $Exports<'react-360-web/js/Modules/WebSocketModule'>;
}
declare module 'react-360-web/js/OVRUI/FourByFourRect/VectorGeometry.js' {
  declare module.exports: $Exports<'react-360-web/js/OVRUI/FourByFourRect/VectorGeometry'>;
}
declare module 'react-360-web/js/OVRUI/SDFFont/DefaultFont.js' {
  declare module.exports: $Exports<'react-360-web/js/OVRUI/SDFFont/DefaultFont'>;
}
declare module 'react-360-web/js/OVRUI/SDFFont/SDFFont.js' {
  declare module.exports: $Exports<'react-360-web/js/OVRUI/SDFFont/SDFFont'>;
}
declare module 'react-360-web/js/OVRUI/UIView/GuiSys.js' {
  declare module.exports: $Exports<'react-360-web/js/OVRUI/UIView/GuiSys'>;
}
declare module 'react-360-web/js/OVRUI/UIView/GuiSysEvent.js' {
  declare module.exports: $Exports<'react-360-web/js/OVRUI/UIView/GuiSysEvent'>;
}
declare module 'react-360-web/js/OVRUI/UIView/UIView.js' {
  declare module.exports: $Exports<'react-360-web/js/OVRUI/UIView/UIView'>;
}
declare module 'react-360-web/js/OVRUI/UIView/UIViewUtil.js' {
  declare module.exports: $Exports<'react-360-web/js/OVRUI/UIView/UIViewUtil'>;
}
declare module 'react-360-web/js/ReactInstance.js' {
  declare module.exports: $Exports<'react-360-web/js/ReactInstance'>;
}
declare module 'react-360-web/js/ReactNativeContext.js' {
  declare module.exports: $Exports<'react-360-web/js/ReactNativeContext'>;
}
declare module 'react-360-web/js/Runtime/Runtime.js' {
  declare module.exports: $Exports<'react-360-web/js/Runtime/Runtime'>;
}
declare module 'react-360-web/js/Utils/__tests__/merge-test.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/__tests__/merge-test'>;
}
declare module 'react-360-web/js/Utils/__tests__/RCTVideoPlayer-test.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/__tests__/RCTVideoPlayer-test'>;
}
declare module 'react-360-web/js/Utils/__tests__/RefCountCache-test.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/__tests__/RefCountCache-test'>;
}
declare module 'react-360-web/js/Utils/__tests__/TextureManager-test.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/__tests__/TextureManager-test'>;
}
declare module 'react-360-web/js/Utils/createRemoteImageManager.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/createRemoteImageManager'>;
}
declare module 'react-360-web/js/Utils/CubePano.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/CubePano'>;
}
declare module 'react-360-web/js/Utils/extractURL.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/extractURL'>;
}
declare module 'react-360-web/js/Utils/fetchResource.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/fetchResource'>;
}
declare module 'react-360-web/js/Utils/FlexboxImplementation.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/FlexboxImplementation'>;
}
declare module 'react-360-web/js/Utils/HPano.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/HPano'>;
}
declare module 'react-360-web/js/Utils/isPositive.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/isPositive'>;
}
declare module 'react-360-web/js/Utils/Math.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/Math'>;
}
declare module 'react-360-web/js/Utils/merge.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/merge'>;
}
declare module 'react-360-web/js/Utils/RCTBindedResource.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/RCTBindedResource'>;
}
declare module 'react-360-web/js/Utils/RCTHeadModel.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/RCTHeadModel'>;
}
declare module 'react-360-web/js/Utils/RCTInputControls.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/RCTInputControls'>;
}
declare module 'react-360-web/js/Utils/RCTResourceManager.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/RCTResourceManager'>;
}
declare module 'react-360-web/js/Utils/RCTVideoPlayer.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/RCTVideoPlayer'>;
}
declare module 'react-360-web/js/Utils/RefCountCache.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/RefCountCache'>;
}
declare module 'react-360-web/js/Utils/ResourceManager.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/ResourceManager'>;
}
declare module 'react-360-web/js/Utils/StereoOffsetRepeats.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/StereoOffsetRepeats'>;
}
declare module 'react-360-web/js/Utils/TextureManager.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/TextureManager'>;
}
declare module 'react-360-web/js/Utils/Yoga.bundle.js' {
  declare module.exports: $Exports<'react-360-web/js/Utils/Yoga.bundle'>;
}
declare module 'react-360-web/js/Video/BasicVideoPlayer.js' {
  declare module.exports: $Exports<'react-360-web/js/Video/BasicVideoPlayer'>;
}
declare module 'react-360-web/js/Video/getSupportedFormats.js' {
  declare module.exports: $Exports<'react-360-web/js/Video/getSupportedFormats'>;
}
declare module 'react-360-web/js/Video/OVRVideo.js' {
  declare module.exports: $Exports<'react-360-web/js/Video/OVRVideo'>;
}
declare module 'react-360-web/js/Video/VRVideoComponent.js' {
  declare module.exports: $Exports<'react-360-web/js/Video/VRVideoComponent'>;
}
declare module 'react-360-web/js/Video/VRVideoPlayer.js' {
  declare module.exports: $Exports<'react-360-web/js/Video/VRVideoPlayer'>;
}
declare module 'react-360-web/js/Views/__tests__/BaseMesh-test.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/__tests__/BaseMesh-test'>;
}
declare module 'react-360-web/js/Views/__tests__/BaseView-test.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/__tests__/BaseView-test'>;
}
declare module 'react-360-web/js/Views/__tests__/Image-test.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/__tests__/Image-test'>;
}
declare module 'react-360-web/js/Views/__tests__/Model-test.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/__tests__/Model-test'>;
}
declare module 'react-360-web/js/Views/__tests__/Text-test.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/__tests__/Text-test'>;
}
declare module 'react-360-web/js/Views/__tests__/View-test.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/__tests__/View-test'>;
}
declare module 'react-360-web/js/Views/AmbientLight.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/AmbientLight'>;
}
declare module 'react-360-web/js/Views/BaseMesh.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/BaseMesh'>;
}
declare module 'react-360-web/js/Views/BaseView.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/BaseView'>;
}
declare module 'react-360-web/js/Views/Box.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/Box'>;
}
declare module 'react-360-web/js/Views/Cylinder.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/Cylinder'>;
}
declare module 'react-360-web/js/Views/CylindricalPanel.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/CylindricalPanel'>;
}
declare module 'react-360-web/js/Views/DirectionalLight.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/DirectionalLight'>;
}
declare module 'react-360-web/js/Views/Image.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/Image'>;
}
declare module 'react-360-web/js/Views/LiveEnvCamera.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/LiveEnvCamera'>;
}
declare module 'react-360-web/js/Views/Model.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/Model'>;
}
declare module 'react-360-web/js/Views/Pano.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/Pano'>;
}
declare module 'react-360-web/js/Views/Plane.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/Plane'>;
}
declare module 'react-360-web/js/Views/PointLight.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/PointLight'>;
}
declare module 'react-360-web/js/Views/Prefetch.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/Prefetch'>;
}
declare module 'react-360-web/js/Views/QuadPanel.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/QuadPanel'>;
}
declare module 'react-360-web/js/Views/RawText.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/RawText'>;
}
declare module 'react-360-web/js/Views/Scene.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/Scene'>;
}
declare module 'react-360-web/js/Views/Sound.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/Sound'>;
}
declare module 'react-360-web/js/Views/Sphere.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/Sphere'>;
}
declare module 'react-360-web/js/Views/SpotLight.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/SpotLight'>;
}
declare module 'react-360-web/js/Views/Text.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/Text'>;
}
declare module 'react-360-web/js/Views/Video.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/Video'>;
}
declare module 'react-360-web/js/Views/VideoPano.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/VideoPano'>;
}
declare module 'react-360-web/js/Views/View.js' {
  declare module.exports: $Exports<'react-360-web/js/Views/View'>;
}
declare module 'react-360-web/React360.js' {
  declare module.exports: $Exports<'react-360-web/React360'>;
}
